### ISSUE TITLE
rsync failed to build on Red Hat 7.3

### ISSUE THREAD

**Issue by horta** [Linuxbrew/homebrew-core#5966]
`brew install rsync `

fails to compile syscall.c:

```
Last 15 lines from /homes/horta/.cache/Homebrew/Logs/rsync/03.make:
                        ^
syscall.c:528:9: warning: implicit declaration of function 'setattrlist' [-Wimplicit-function-declaration]
  return setattrlist(path, &attrList, &ts, sizeof ts, FSOPT_NOFOLLOW);
         ^
syscall.c:528:54: error: 'FSOPT_NOFOLLOW' undeclared (first use in this function)
  return setattrlist(path, &attrList, &ts, sizeof ts, FSOPT_NOFOLLOW);
                                                      ^
syscall.c:516:18: warning: unused variable 'attrList' [-Wunused-variable]
  struct attrlist attrList;
                  ^
syscall.c:529:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [syscall.o] Error 1
```

Similar problem found at https://github.com/Linuxbrew/homebrew-core/pull/5864

Gist: https://gist.github.com/3c237fad14b1c7f55db27490af03c528

**Comment by iMichka** [comment]
Hi. Thanks for reporting this. As you saw, I already saw the error. The thing is that I do not have much time to look at this. The best thing would be contact the rsync developers and ask them if they know why this is failing to build. Thanks!

**Comment by iMichka** [comment]
Should be fixed by #5864, I removed the mac patches, and am building stock `rsync` now.

**Comment by jwhite007** [comment]
@iMichka Thanks a lot, sir. I can confirm that the rsync installation now works properly... both `brew install rsync` and `brew install rsync --build-from-source`.

Red Hat Enterprise Linux Server release 6.6
