### PR TITLE
re2: -lpthread strangely needed

### PR DESCRIPTION
**Pull request by rwhogg**

### CODE REVIEW

**Comment by rwhogg** [comment]
From https://travis-ci.org/Linuxbrew/homebrew-core/builds/155723824#L421

```
Error: The selected compiler doesn't support C++11: gcc
```

The default GCC on 12.04 doesn't completely support C++ 11 (it has partial support of "C++ 0x").

**Comment by maxim-belkin** [comment]
Maybe try adding `depends_on "gcc"`? Not 100% sure that 5.3.0 will help, but 6.1.x should.

**Comment by rwhogg** [comment]
>  Not 100% sure that 5.3.0 will help, but 6.1.x should.

As it turns out, this formula's a whole bunch of crazy:

```
  needs :cxx11

  # https://github.com/google/re2/issues/102                                                                                                  
  # https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70932                                                                                        
  fails_with :gcc => "6" do
    cause "error: field 'next_' has incomplete type 'std::atomic<re2::DFA::State*> []'"
  end

  needs :cxx11 unless OS.mac?

  def install
    ENV.cxx11
    ...
```

Two different `needs :cxx11`'s, a failure on GCC 6, and specifically saying `ENV.cxx11` - this formula is *very* picky about C++.

Given that the purpose of Travis is to test that something will work with the default 12.04 compiler on a normalish Ubuntu system, and that's obviously never going to happen, I'm tempted to just ignore Travis. But since it's C++, that means ABI problems, so it might actually be best just not to bottle this for now.

**Comment by sjackman** [comment]
I'm okay with ignoring the Travis error and bottling `re2`. The most important role of Travis is to test that bottles built on Ubuntu 14 work on Ubuntu 12. It's good if it's possible to build from source on Travis, but not strictly necessary.

**Comment by sjackman** [comment]
test fails on Circle
```
==> brew test re2 --verbose
Testing re2
==> /usr/bin/g++-4.8 -std=c++11 -I/home/linuxbrew/.linuxbrew/Cellar/re2/20161101/include -L/home/linuxbrew/.linuxbrew/Cellar/re2/20161101/lib -lre2 test.cpp -o test
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/re2/test.01.g++-4.8:
2016-12-07 17:04:57 +0000

/usr/bin/g++-4.8
-std=c++11
-I/home/linuxbrew/.linuxbrew/Cellar/re2/20161101/include
-L/home/linuxbrew/.linuxbrew/Cellar/re2/20161101/lib
-lre2
test.cpp
-o
test

/tmp/ccWwmU9P.o: In function `main':
test.cpp:(.text+0x1c): undefined reference to `re2::RE2::RE2(char const*)'
test.cpp:(.text+0x75): undefined reference to `re2::RE2::~RE2()'
test.cpp:(.text+0x89): undefined reference to `re2::RE2::RE2(char const*)'
test.cpp:(.text+0xe2): undefined reference to `re2::RE2::~RE2()'
test.cpp:(.text+0xfb): undefined reference to `re2::RE2::~RE2()'
test.cpp:(.text+0x118): undefined reference to `re2::RE2::~RE2()'
/tmp/ccWwmU9P.o: In function `bool re2::RE2::FullMatch<>(re2::StringPiece const&, re2::RE2 const&)':
test.cpp:(.text._ZN3re23RE29FullMatchIIEEEbRKNS_11StringPieceERKS0_DpOT_[_ZN3re23RE29FullMatchIIEEEbRKNS_11StringPieceERKS0_DpOT_]+0x26): undefined reference to `re2::RE2::FullMatchN(re2::StringPiece const&, re2::RE2 const&, re2::RE2::Arg const* const*, int)'
/tmp/ccWwmU9P.o: In function `bool re2::RE2::PartialMatch<>(re2::StringPiece const&, re2::RE2 const&)':
test.cpp:(.text._ZN3re23RE212PartialMatchIIEEEbRKNS_11StringPieceERKS0_DpOT_[_ZN3re23RE212PartialMatchIIEEEbRKNS_11StringPieceERKS0_DpOT_]+0x26): undefined reference to `re2::RE2::PartialMatchN(re2::StringPiece const&, re2::RE2 const&, re2::RE2::Arg const* const*, int)'
collect2: error: ld returned 1 exit status
Error: re2: failed
Failed executing: /usr/bin/g++-4.8 -std=c++11 -I/home/linuxbrew/.linuxbrew/Cellar/re2/20161101/include -L/home/linuxbrew/.linuxbrew/Cellar/re2/20161101/lib -lre2 test.cpp -o test
```

**Comment by sjackman** [comment]
The test failure should hopefully be easily fixed by changing `-lre2 test.cpp` to `test.cpp -lre2`.

**Comment by rwhogg** [comment]
No dice:

```
Testing re2
==> /usr/bin/g++-5 -std=c++11 -I/home/linuxbrew/.linuxbrew/Cellar/re2/20161101/include -L/home/linuxbrew/.linuxbrew/Cellar/re2/20161101/lib test.cpp -lre2 -o test
/home/linuxbrew/.linuxbrew/Cellar/re2/20161101/lib/libre2.a(regexp.o): In function `void std::__once_call_impl<std::_Bind_simple<re2::Regexp::Incref()::{lambda()#1} ()> >()':
regexp.cc:(.text+0x16): undefined reference to `pthread_rwlock_init'
/home/linuxbrew/.linuxbrew/Cellar/re2/20161101/lib/libre2.a(regexp.o): In function `re2::Mutex::Lock()':
regexp.cc:(.text._ZN3re25Mutex4LockEv[_ZN3re25Mutex4LockEv]+0x2): undefined reference to `pthread_rwlock_wrlock'
/home/linuxbrew/.linuxbrew/Cellar/re2/20161101/lib/libre2.a(regexp.o): In function `re2::MutexLock::~MutexLock()':
regexp.cc:(.text._ZN3re29MutexLockD2Ev[_ZN3re29MutexLockD5Ev]+0x5): undefined reference to `pthread_rwlock_unlock'
/home/linuxbrew/.linuxbrew/Cellar/re2/20161101/lib/libre2.a(dfa.o): In function `re2::Mutex::Mutex()':
dfa.cc:(.text._ZN3re25MutexC2Ev[_ZN3re25MutexC5Ev]+0x4): undefined reference to `pthread_rwlock_init'
/home/linuxbrew/.linuxbrew/Cellar/re2/20161101/lib/libre2.a(dfa.o): In function `re2::Mutex::~Mutex()':
dfa.cc:(.text._ZN3re25MutexD2Ev[_ZN3re25MutexD5Ev]+0x2): undefined reference to `pthread_rwlock_destroy'
/home/linuxbrew/.linuxbrew/Cellar/re2/20161101/lib/libre2.a(dfa.o): In function `re2::Mutex::ReaderLock()':
dfa.cc:(.text._ZN3re25Mutex10ReaderLockEv[_ZN3re25Mutex10ReaderLockEv]+0x2): undefined reference to `pthread_rwlock_rdlock'
/home/linuxbrew/.linuxbrew/Cellar/re2/20161101/lib/libre2.a(dfa.o): In function `re2::Mutex::ReaderUnlock()':
dfa.cc:(.text._ZN3re25Mutex12ReaderUnlockEv[_ZN3re25Mutex12ReaderUnlockEv]+0x2): undefined reference to `pthread_rwlock_unlock'
collect2: error: ld returned 1 exit statu
```
Also linking against pthreads solves this issue.

**Comment by sjackman** [comment]
It shouldn't be necessary to explicitly list `-lpthread` on the link line like `test.cpp -lre2 -lpthread` if `-lpthread` is listed in the `NEEDED` dependencies of `libre2.so`. Try
```sh
patchelf --print-needed libre2.so
```

**Comment by rwhogg** [comment]
```bash
% patchelf --print-needed ~/.linuxbrew/opt/re2/lib/libre2.so.0
libstdc++.so.6
libgcc_s.so.1
libpthread.so.0
libc.so.6
ld-linux-x86-64.so.2
```

It's weird, the `-lpthread` is necessary locally too. Not sure what gives.
