### ISSUE TITLE
systemd failed to build on debian(stable)

### ISSUE THREAD

**Issue by sfolje0** [Linuxbrew/homebrew-core#1943]
cannot install systemd running `brew install systemd`. It stops at `==> make install` step.
gist from `brew gist-logs systemd`: [https://gist.github.com/6658a7f48c589e9930e4372c69f86506](https://gist.github.com/6658a7f48c589e9930e4372c69f86506)
abstract excerpt:
```
libtool compile ...
In file included from src/basic/arphrd-list.c:31:0:
src/basic/arphrd-from-name.h:125:1: error: conflicting types for 'lookup_arphrd'
 lookup_arphrd (register const char *str, register size_t len)
 ^
src/basic/arphrd-list.c:28:34: note: previous declaration of 'lookup_arphrd' was here
 static const struct arphrd_name* lookup_arphrd(register const char *str, register unsigned int len);

Makefile:14189: recipe for target 'src/basic/libbasic_la-arphrd-list.lo' failed
make[2]: *** [src/basic/libbasic_la-arphrd-list.lo] Error 1
libtool compile ...
Makefile:18384: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
Makefile:19618: recipe for target 'install' failed
make: *** [install] Error 2
```

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `systemd`.
Another possible workaround for you is `brew install --force-bottle systemd`, but no promises that will work.

**Comment by sjackman** [comment]
`systemd` fails to build with `gperf` 3.1. Possible options are to add a `gperf@3.0` formula if this issue affects other formulas other than `systemd`.

This patch should resolve this issue.
https://github.com/systemd/systemd-stable/commit/79a5d862a7abe903f456a75d6d1ca3c11adfa379.patch

**Comment by sjackman** [comment]
This PR https://github.com/Linuxbrew/homebrew-core/pull/1946 may resolve your issue.

**Comment by sjackman** [comment]
@sfolje0 Try installing `systemd` 232 like so:
```sh
brew install https://raw.githubusercontent.com/sjackman/homebrew-core/31e97778d29de48862be33b8f95294010679a6d7/Formula/systemd.rb
```

**Comment by 7kemZmani** [comment]
@sfolje0 
>brew install https://raw.githubusercontent.com/sjackman/homebrew-core/31e97778d29de48862be33b8f95294010679a6d7/Formula/systemd.rb

The problem is still there

**Comment by sjackman** [comment]
Yes, this issue was not resolved. Please comment over at #1946.
