### PR TITLE
epstool: open with O_CREAT in second argument needs 3 arguments

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
Builds fine on Travis with GCC 4.6 but fails on Circle with GCC 4.8.
```
/usr/bin/gcc-4.8 -I./src -I./epsobj -Os -w -pipe -march=core2 -DX11 -DUNIX -DNONAG  -Wall -Wstrict-prototypes -Wmissing-declarations -Wmissing-prototypes -fno-builtin -fno-common -Wcast-qual -Wwrite-strings  -g      -o ./epsobj/ceps.o -c ./src/ceps.c
make: *** [epsobj/xnodll.o] Error 2
make: *** Waiting for unfinished jobs....
In file included from /usr/include/fcntl.h:279:0,
                 from ./src/epstool.c:41:
In function ‘open’,
    inlined from ‘exec_program.constprop.4’ at ./src/epstool.c:2827:13:
/usr/include/x86_64-linux-gnu/bits/fcntl2.h:50:24: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT in second argument needs 3 arguments
    __open_missing_mode ();
                        ^
```

**Comment by maxim-belkin** [comment]
will reinitiate the build.

**Comment by maxim-belkin** [comment]
https://github.com/Linuxbrew/homebrew-core/pull/2168

**Comment by sjackman** [comment]
#2168 built successfully. :tada: Possibly `--env-super` is to be thanked.

**Comment by maxim-belkin** [comment]
that and [this](https://github.com/Linuxbrew/homebrew-core/pull/2168/commits/21137853f59cd5fa172eab26c9236da737d0767c#diff-d9f03acb2be87f310a241e402f067bdbR19)
