### ISSUE TITLE
glog build fails

### ISSUE THREAD

**Issue by ahundt** [Linuxbrew/homebrew-core#2873]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] Attempt to replicate the problem on macOS with Homebrew if possible. If you can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)

The main issue I was attempting to install glog on ubuntu 16.04
https://gist.github.com/a4928686de751e099e273744ed0afbe0

`brew install glog`

Side note: I then tried improving the glog.rb formula, which I submitted upstream at https://github.com/Homebrew/homebrew-core/pull/14379, but that change also fails to compile on 16.04 (16.04 gist log with that pull request incorporated: https://gist.github.com/9276678134230340b547fd8a2c326bd3). The updated `glog.rb` formula itself works on OS X but some downstream formulae currently don't link properly.

**Comment by sjackman** [comment]
```
libtool: link: g++-5 -pthread -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -DNO_FRAME_POINTER -g -O2 -pthread -o .libs/utilities_unittest src/utilities_unittest-utilities_unittest.o  ./.libs/libglog.so -lgflags -lpthread -pthread -Wl,-rpath -Wl,/home/linuxbrew/.linuxbrew/Cellar/glog/0.3.5_1/lib
./.libs/libglog.so: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
collect2: error: ld returned 1 exit status
Makefile:1073: recipe for target 'logging_striptest2' failed
```
https://gist.github.com/anonymous/a4928686de751e099e273744ed0afbe0#file-02-make-L83

**Comment by sjackman** [comment]
Attempting to reproduce this build failure at https://github.com/Linuxbrew/homebrew-core/pull/2876
As a workaround, try
```sh
brew install gflags
brew install gcc@4.9
brew install --cc=gcc-4.9 glog
```

**Comment by ahundt** [comment]
That workaround succeeded, thanks!

**Comment by sjackman** [comment]
I've merged PR #2876, which was successful. `brew install glog` should work now.

**Comment by ahundt** [comment]
yep it poured the bottle, thanks again

**Comment by sjackman** [comment]
No worries. Happy to help.
