### ISSUE TITLE
epstool failed to build on Ubuntu 

### ISSUE THREAD

**Issue by nir-krakauer** [Linuxbrew/homebrew-core#959]
`make install` fails with messages similar to `Fatal error: can't create ./epsobj/epstool.o: No such file or directory`

This [old MacPorts bug report](https://trac.macports.org/ticket/40613) seems possibly related?

[Gist](https://gist.github.com/72f46c60aa161016c453574974a95199)

**Comment by nir-krakauer** [comment]
Oddly, on repeating, the error message is different: `call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments`

[Gist](https://gist.github.com/anonymous/c54f48636083dd1f16cd2e9261441681)

**Comment by sjackman** [comment]
I'm attempting to reproduce the issue over at #999

**Comment by sjackman** [comment]
`epstool` builds fine on Travis with GCC 4.6 but fails on Circle with GCC 4.8.
```
/usr/bin/gcc-4.8 -I./src -I./epsobj -Os -w -pipe -march=core2 -DX11 -DUNIX -DNONAG  -Wall -Wstrict-prototypes -Wmissing-declarations -Wmissing-prototypes -fno-builtin -fno-common -Wcast-qual -Wwrite-strings  -g      -o ./epsobj/ceps.o -c ./src/ceps.c
make: *** [epsobj/xnodll.o] Error 2
make: *** Waiting for unfinished jobs....
In file included from /usr/include/fcntl.h:279:0,
                 from ./src/epstool.c:41:
In function ‘open’,
    inlined from ‘exec_program.constprop.4’ at ./src/epstool.c:2827:13:
/usr/include/x86_64-linux-gnu/bits/fcntl2.h:50:24: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT in second argument needs 3 arguments
    __open_missing_mode ();
                        ^
```

**Comment by VonUniGE** [comment]
`epstool` build fine on GCC 6.3.0, (the version from Debian 9) and on GCC 5.3.0 (the version from Linuxbrew).
Is it possible to force the use of the GCC from Linuxbrew or should formulas support all versions of GCC?

**Comment by sjackman** [comment]
`epstool` has a bottle now. It's marked as `fails_with :gcc => "4.8"` so it will build with GCC 5.3 on Linuxbrew.
